#pragma once

// background vivid color
#define BG_BLACK        0x00
#define BG_GRAY         BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_RED
#define BG_WHITE        BG_GRAY | BACKGROUND_INTENSITY
#define BG_RED          BACKGROUND_RED | BACKGROUND_INTENSITY
#define BG_GREEN        BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define BG_BLUE         BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define BG_YELLOW       BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define BG_CYAN         BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define BG_MAGENTA      BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY

// background dark color
#define BG_D_RED        BACKGROUND_RED
#define BG_D_GREEN      BACKGROUND_GREEN
#define BG_D_BLUE       BACKGROUND_BLUE
#define BG_D_YELLOW     BACKGROUND_RED | BACKGROUND_GREEN
#define BG_D_CYAN       BACKGROUND_BLUE | BACKGROUND_GREEN
#define BG_D_MAGENTA    BACKGROUND_RED | BACKGROUND_BLUE

// foreground vivid color
#define FG_BLACK        0x00
#define FG_GRAY         FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED
#define FG_WHITE        FG_GRAY | FOREGROUND_INTENSITY
#define FG_RED          FOREGROUND_RED | FOREGROUND_INTENSITY
#define FG_GREEN        FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define FG_BLUE         FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define FG_YELLOW       FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define FG_CYAN         FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define FG_MAGENTA      FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY

// foreground dark color
#define FG_D_RED        FOREGROUND_RED
#define FG_D_GREEN      FOREGROUND_GREEN
#define FG_D_BLUE       FOREGROUND_BLUE
#define FG_D_YELLOW     FOREGROUND_RED | FOREGROUND_GREEN
#define FG_D_CYAN       FOREGROUND_BLUE | FOREGROUND_GREEN
#define FG_D_MAGENTA    FOREGROUND_RED | FOREGROUND_BLUE
